---
output: html_document
---

# Kasteel(park) Lembeek

**eigenaar:** Stad Halle
**toegankelijkheid**: het kasteelpark is vrij toegankelijk.

## Het kasteel weerspiegeld in Zenne.

Gedurende 3 eeuwen was dit bouwwerk het statige machtssymbool van de heren van Lembeek. De families Richardot, Bornonville, d'Ursel.
In 1853 kocht Paul Claes, die in Lembeek een grote jeneverstokerij had, het kasteel en liet het restaureren.
In 1904 verkochten de erfgenamen van P. Claes het kasteeldomein aan de Broeders der Christelijke scholen. De congregatie voorheen gevestigd in Frankrijk, was op zoek naar een nieuwe vestigingsplaats in het buitenland voor haar administratieve hoofdzetel.
Het kasteeldomein was evenwel niet voorzien op de grote toevloed van religieuzen. Er werd in spoedtempo werk gemaakt van aanpassingswerken. 
De broeders respecteerden de oorspronkelijke constructie en gebruikten dezelfde materialen.
De nieuwe gebouwen omvatten o.a. een klein en een tweede noviciaat met klaslokalen en de slaapzaal voor de novicen. Hier werden telkens een 50-tal Broeders van over de hele wereld (o.a. uit Frankrijk, V.S., Italië, Canada, Ierland, Duitsland, Spanje, Oostenrijk, Ceylon...) verder ingewijd in het gedachtengoed van J.-B. de la Salle gedurende 9 maanden. 
Zo raakten Lembeek en zijn kasteel bekend in de 5 werelddelen en was het er een komen en gaan van mensen van over de hele wereld. Tot 1936 bleef Lembeek de administratieve hoofdzetel van de congregatie.


In 1971 verkochten de Broeders hun domein in Lembeek aan de "Etablissementen Fr. Colruyt". Die zouden er magazijnen bouwen!! Waarvoor ze toestemming kregen van het toenmalig gemeentebestuur... Nog geen jaar later was het grootste deel van het kasteel afgebroken.

Wat er nu nog staat zijn o.a. het gerestaureerde klein noviciaat, grenzend aan de Bondgenotenstraat, en ernaast de toegangspoort tot het Kasteelpark. Hierin zijn nu het lokaal van de Chiromeisjes en de pingpongclub ondergebracht.
In het dak van dit gebouw zijn er aan de kant van de Bondgenotenstraat invliegopeningen voor vleermuizen ondergebracht. 

Bronnen:
- Lembeek in oude prenten deel 1 en 2 / Dirk Vandenplas

Info vind je ook op :

- http://home.scarlet.be/~tsf13331/toenennu/ligging-infra.htm
- https://berichtenuithetverleden.wordpress.com/2010/12/27/de-malakoff-toren-te-lembeek/

### Inrichting voor vleermuizen

Op de zolder van de kloostergebouwen werden een aantal invliegopeningen geplaatst. Deze openingen laat toe dat enkel vleermuizen makkelijk binnen en buiten kunnen vliegen. Vleermuizen maken tijdens de zomer graag gebruik van dergelijke zolders om overdag te slapen.

## Wat eten vleermuizen?

Alle vleermuizen die in onze streken voorkomen eten insecten en spinnen. Sommige tropische soorten zijn verzot op fruit, nectar of vis.

Vleermuizen gebruiken verschillende technieken om hun prooi te pakken te krijgen. Voor vliegende prooien gebruiken de vleermuizen meestal hun staarthuid als een soort schepnet. De staarthuid is een dun vlies dat tussen de achterpoten en de staart van vleermuizen zit. Vervolgens nemen ze de prooi met hun mond vast. Muggen worden in de vlucht opgegeten, deze zijn klein genoeg om snel door te slikken. Nachtvlinders of kevers zijn te groot om in een keer door te slikken. De vleermuis vliegt dan naar een boom en hangt ondersteboven aan een tak waarna de prooi opgegeten wordt.

Watervleermuizen en meervleermuizen jagen op insecten die op het water zitten. Deze soorten hebben extra grote voeten waarmee ze insecten van het wateroppervlak harken.

Dagactieve insecten zijn evenmin veilig voor vleermuizen. 

### Wist je dat... 

... een vleermuis elke nacht de helft van zijn eigen gewicht opeet. Reken maar uit hoeveel muggen dat zijn als je weet dat een mug slechts 0.0025 gram weegt.

... vampiervleermuizen echt bestaan. Ze hebben slijmscherpe tanden waarmee ze een wondje maken bij hun slachtoffer waarna ze het bloed oplikken. Gelukkig komen deze vleermuizen enkel in Midden-Amerika voor!

### Video's

Jagende vleermuizen  
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/p08Y0oRAX3g?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Vertraagde opname van jagende vleermuis
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/el9RJL72vRA?showinfo=0" frameborder="0" allowfullscreen></iframe>


## Franjestaart

### Weetjes

- Als ik mijn vleugels spreid, ben ik 24 tot 28 cm breed.
- Ik weeg 5 tot 12 gram.
- Als ik honger heb, zoek ik insecten in bossen en parken. Hierbij ga ik op zoek naar dagactieve insecten die slapen op de bladeren.
- Tijdens de zomer slaap ik overdag graag in een oud spechtenhol of een andere holte in een boom
- Tijdens de winter verstop ik met liefst in een grot. Ondergrondse bouwsels zoals tunnels of forten die een beetje op een grot lijken vind ik ook prima. Als het maar rustig, donker en vochtig is.

### Video's

Franjestaarten vliegen 's avonds uit de kolonie in een boom
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/Y7CLEdDgd1A?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Franjestaarten in een holle robinia
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/LMWT-iG39Cc?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Vertraagde opname van een Franjestaart die opvliegt
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/o5-QIR4bgbM?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/us1dFwR_ZXY?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Franjestaarten in winterslaap
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/bfmDAva7vbk?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
