---
output: html_document
---

# Sint Vincentiuskerk

**eigenaar:** kerkfabriek Sint Vincentiuskerk
**toegankelijkheid:** de kerk zelf is enkel toegankelijk tijdens de erediensten. De zolder is enkel toegankelijk voor vleermuizen.

## Sint Vincentiuskerk

De kerk dateert van het begin van vorige eeuw, en werd gebouwd ter vervanging van de kleinere St. Vincentiuskerk die aan de overkant van het plein naast de Kasteelhoeve stond en die op haar beurt werd gebouwd ter vervanging van de kapel van het Kasteel van Buizingen.
Op de huidige kerk is er nooit een toren gebouwd. Vandaar de naam “Kerk zonder toren”

Meer info nodig?

Buizingen zoals het vroeger was/ Guy Lernout en Erik Meeussen

Of  digitaal:

- http://www.kerkeninvlaanderen.be/pages/kerk_01370.htm
- https://nl.wikipedia.org/wiki/Sint-Vincentiuskerk_(Buizingen)
- http://www.bezieldverband.be/gemeenschap/don-boscoparochie-buizingen
- https://nl.wikipedia.org/wiki/Buizingen
- http://www.nieuwsblad.be/cnt/blide_02528307


## Zomerkolonies van vleermuizen

Twee dakramen van de kerk werden aangepast zodat de vleermuizen ze als invliegopening kunnen gebruiken.

## Vleermuizen zijn bedreigd en hebben geschikte verblijfsplaatsen nodig

Vleermuizen gebruiken een verblijfplaats voor de winterslaap, in de zomer zijn er verblijfplaatsen om te slapen, te paren, voedsel te verorberen, jongen groot te brengen en als tussenstop tijdens de trek. Op basis van het soort verblijfplaats kunnen vleermuizen worden ingedeeld in twee typen, soorten die gebruik maken van holten en spleten in bomen en vleermuizen die gebruik maken van bebouwing.

In bebouwing wordt bijvoorbeeld gebruik gemaakt van spouwruimten, ruimte achter beplating, zolders, kelders, kerktorens en dak bekleding. Soorten als de Gewone dwergvleermuis verkiezen smalle ruimten, waar zij zowel met de buik als met de rug in contact staan met het substraat; spouwmuren zijn een favoriet verblijf. Andere soorten hangen vrij, bijvoorbeeld aan balken op kerkzolders.  Het aantal dieren dat van een verblijfplaats gebruik maakt kan variëren van een enkel exemplaar tot vele honderden exemplaren en hangt af van de soort en het type gebruik. Tijdens de kraamtijd komen bijvoorbeeld grote groepen vrouwtjes samen, om gezamenlijk jongen te baren. Later in het jaar, wanneer de jonge dieren uitvliegen, vallen dergelijke groepen uiteen in kleine groepjes. De samenhang in deze groep dieren is blijvend van karakter, men spreekt dan ook van een kolonie. Veel soorten vleermuizen onderhouden een netwerk van (zomer)verblijfplaatsen. Om een gebied, bijvoorbeeld een bedrijfsterrein, geschikt te maken voor bewoning door vleermuizen, wordt dan ook geadviseerd meerdere verblijfplaatsen te creëren.

De mogelijkheden zijn eindeloos om bijvoorbeeld bij verbouwingen verblijfplaatsen te realiseren. Er zijn wel voorwaarden aan verbonden:

- de betreffende ruimte is bereikbaar voor vleermuizen door invliegopeningen;
- de invliegopening(en) is (zijn) vrij van verstoring (bijvoorbeeld verlichting);
- de ruimte is droog en niet tochtig;
- in en rond de ruimte vindt geen verstoring plaats (betreding door mensen, trillingen, licht);
- de ruimte is vrij van irriterende stoffen als gif, houtbehandelingsmiddelen en kleverige harsen;
- de ruimte is warm of warmt snel op;
- in de ruimte zijn mogelijkheden voor vleermuizen om aan te hangen (ruw materiaal als onbehandeld hout, niet gepolijst steenwerk) of tussen weg te kruipen (spleten, kieren);
- de ruimte is niet toegankelijk voor predatoren (er zijn voorbeelden bekend van katten die bij de uitvliegopening wachten op in- of uitvliegende vleermuizen)  


### Invliegopeningen: wat kan u zelf doen voor de vleermuis

Liggende chiroptières, dakramen, verluchtingsgaten     

- Een dakraam kan fungeren als chiroptière. Het is voldoende om het raam te fixeren met een opening van maximum 6 cm. Een houten onderrand vergemakkelijkt het binnen kruipen. Verdonkeren van de dakramen is aan te raden. Dat maakt de achterliggende ruimte ongeschikt voor vogels.De zijkanten van het dakvenster afwerken met zink voorkomt binnen regenen.

- Bij gewone ramen kunnen invliegopeningen worden voorzien als het raamkozijn dat toelaat.Eén of meerdere vensters vervangen door een plank met een opening van maximum 6 cm bij 40 cm is een alternatief om vleermuizen toegang te verlenen via bestaande ramen.

- (Kerk)zolders met glazen ramen kan men verdonkeren door het plaatsen van ondoorzichtige panelen achter het glas. Het glas beschilderen is minder geschikt aangezien verf onder invloed van licht en temperatuurverschillen gemakkelijk afschilfert. Door het verdonkeren van de kerkzolder maakt men de zolder meer geschikt voor vleermuizen en houdt men duiven, die donkere ruimtes zoveel mogelijk vermijden.

Meer info en afbeeldingen: https://www.ecopedia.be/pagina/inventariseren-van-kerkzolders-op-vleermuizen

<iframe src="https://player.vimeo.com/video/149653792" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/149653792">13 Vleermuizen op zolder</a> from <a href="https://vimeo.com/inverde">Inverde</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

<iframe src="https://player.vimeo.com/video/151408387" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/151408387">Hoe een kerkzolder inrichten voor vleermuizen?</a> from <a href="https://vimeo.com/inverde">Inverde</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

## Laatvlieger

### Weetjes

- Als ik mijn vleugels spreid, ben ik 31 tot 38 cm breed.
- Ik weeg 14 tot 35 gram.
- Ik ben verzot op allerlei grote insecten.
- Zowel zomers als winter verblijf ik overdag graag op een zolder of in een spouwmuur.

### Video's

<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/suEs0KzJUcI?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/7paEX5d-TqA?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/nVOv80yFD1o?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/-e9IQGQVfG4?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>
