---
title: "Oude spoorwegbedding"
output: html_document
---

## Vleermuizen en kleine landschapselementen

Vleermuizen zenden ultrasone signalen uit die hier en daar weerkaatsen op wat er aanwezig is in de nabije omgeving: enkele huizen, een boom, wat struiken, een bosrand, enz. ... . Deze voorwerpen noemen we landschapselementen. De vleermuizen vangen de weerkaatste signalen op en kunnen zich hierdoor een beeld vormen van de omgeving. Dit systeem noemt men echolocatie.
Meteen is duidelijk waarom gebouwen, enkele bomen, een dreef, een bosrand, of zoals op deze plek een oude spoorwegbedding met 2 bermen met struiken en bomen, zo belangrijk zijn voor vleermuizen om zich te oriënteren.
In een open landschap, een weide bv., raakt een vleermuis letterlijk (en figuurlijk) het Noorden kwijt.
Deze landschapselementen zijn tevens een geschikt biotoop voor veel insecten, dewelke dan weer een belangrijke voedselbron voor de vleermuizen zijn.

## Gewone grootoorvleermuis

### Weetjes

- Als ik mijn vleugels spreid, ben ik 24 tot 29 cm breed.
- Ik weeg 4.6 tot 11.3 gram.
- Mijn oren zijn bijna even lang als mijn lichaam. Om ze in de winter te beschermen stop ik ze onder mijn vleugels.
- Mijn vleugels zijn heel breed waardoor ik traag en zeer wendbaar kan vliegen. Ik kan zelfs stilhangen in de lucht.
- Als ik honger heb, zoek ik insecten in bossen en parken. Hierbij ga ik op zoek naar dagactieve insecten die slapen op de bladeren.
- Tijdens de zomer slaap ik overdag graag in een oud spechtenhol of een andere holte in een boom
- Tijdens de winter zit ik graag in behoorlijk koud plaatsen. Een boomholte is prima. Als het echt koud wordt, kan je mij ook in bunkers, ijskelder en grotten vinden.

### Video's

Grootoorvleermuis vliegt uit een boomholte
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/nRbkZOgIeTA?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Grootoorvleermuis vliegt rond in een revalidatiekooi
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/YHZR4BWmQsQ?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>


- eigenaar: stad Halle? Openbaar domein?
- nut voor vleermuizen: vliegroute/jachtgebied
- inrichting: geen
- geschiedenis: oude spoorweg. http://www.railations.net/oudespoorbeddingen.html
- vleermuis toegelicht: gewone grootoorvleermuis

