---
title: "Bat Bike"
output: html_document
---

De Vleermuizenwerkgroep Myotis werd opgericht op 1 augustus 2016.

Het is een werkgroep van enthousiaste vrijwilligers die instaat  voor de werking rond vleermuizen in de regio Zuidwest-Brabant.  Het gaat om onderzoek, bescherming en educatie.

De werkgroep neemt deel aan wintertellingen: jaarlijks worden de overwinteringsobjecten geïnventariseerd. Bunkers, ijskelders en kelders zijn de favoriete overwinteringsplaatsen van de  gewone grootoorvleermuis, koesterbuur van de stad Halle.

Het zomeronderzoek bestaat uit inventarisatie,  het ontdekken en het opvolgen van zomerkolonies. Dit gebeurt door batdetector onderzoek.

De vleermuizenwerkgroep Myotis wil zoveel mogelijk zomer- en winterverblijven inrichten en zal eveneens trachten mensen te sensibiliseren door voor het grote publiek vleermuisactiviteiten te organiseren, zoals cursussen en vleermuiswandelingen.

Zo zal gedurende de Europese Nacht van de Vleermuis elk jaar op een andere locatie een info avond met gidsbeurt georganiseerd worden.   

Wie vragen heeft over vleermuizen, verblijfplaatsen, een vleermuis gevonden, de wandelingen, lid wenst te worden, kan contact opnemen met de werkgroep via mail  myotis.vleermuizenwerkgroep@gmail.com of telefonisch 0479/59 22 59.

Leden van de werkgroep zijn : Jan Van Schepdael, Luc De Ridder, Pierre Kestemont, Christine Goessens, Thierry Onkelinx
