---
title: "Malakoffdomein (Grote Zenne)"
output: html_document
---

## Wat eten vleermuizen?

Alle vleermuizen die in onze streken voorkomen eten insecten en spinnen. Sommige tropische soorten zijn verzot op fruit, nectar of vis.

Vleermuizen gebruiken verschillende technieken om hun prooi te pakken te krijgen. Voor vliegende prooien gebruiken de vleermuizen meestal hun staarthuid als een soort schepnet. De staarthuid is een dun vlies dat tussen de achterpoten en de staart van vleermuizen zit. Vervolgens nemen ze de prooi met hun mond vast. Muggen worden in de vlucht opgegeten, deze zijn klein genoeg om snel door te slikken. Nachtvlinders of kevers zijn te groot om in een keer door te slikken. De vleermuis vliegt dan naar een boom en hangt ondersteboven aan een tak waarna de prooi opgegeten wordt.

### Wist je dat... 

... vampiervleermuizen echt bestaan. Ze hebben slijmscherpe tanden waarmee ze een wondje maken bij hun slachtoffer waarna ze het bloed oplikken. Gelukkig komen deze vleermuizen enkel in Midden-Amerika voor!

... een vleermuis echt nacht de helft van zijn eigen gewicht opeet. Reken maar uit hoeveel muggen dat zijn als je weet dat een mug slechts 0.0025 gram weegt.

### Video's

Jagende vleermuizen  
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/p08Y0oRAX3g?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>


## Watervleermuis

**Foto van watervleermuis in een spechtenhol**

### Weetjes

- Als ik mijn vleugels spreidt ben ik 24 tot 28 cm breed.
- Ik weeg gewicht 7 tot 17 gram.
- Ik ben verzot op muggen en andere insecten die boven water vliegen. Mijn grote voeten gebruik ik om de insecten van het water te scheppen.
- Tijdens de zomer slaap ik overdag graag in een oud spechtenhol of een andere holte in een boom
- Tijdens de winter verstop ik met liefst in een grot. Ondergrondse bouwsels zoals tunnels of forten die een beetje op een grot lijken vind ik ook prima. Als het maar rustig, donker en vochtig is.

### Video's

Watervleermuis schept een insect van het wateroppervlak  
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/Gxy5Gjb-cSw?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Watervleermuis jaagt boven een rivier (nachtkijker)  
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/j_6zvF7kQOw?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

Een kolonie watervleermuizen in een holle boom  
<iframe width="640" height="360" src="https://www.youtube-nocookie.com/embed/eZQ8q0isNYE?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>


# Op te kuizen info

- eigenaar: Agentschap voor Natuur- en Bos
- nut voor vleermuizen:
    - winterverblijfplaats
    - jachtgebied
- inrichting:
    - kelder
        - filmpje met binnenzicht kelder. Eventueel te maken tijdens een volgende telling.
- geschiedenis: 
    - http://www.hallerbos.be/bezoekersinfo/verdronken-toren/
    - http://www.gs-esf.be/downloads/topoguides/Lembeek05_NL_LOW_A4.pdf
- vleermuis toegelicht: watervleermuis
    - foto
    - silhouet?
    - beknopte levenswijze
    - kenmerken voor leken
        - jaagt vlak boven water

<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/kmq-aYFfD68?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

- detailkaart:
    - fietsroute
    - wandelroute
    - infobord
    - ingang kelder
    - toren
- meer info:
    - https://www.natuurenbos.be/malakoffdomein
