---
title: "Detailkaart"
output: html_document
---

```{r load_packages, include = FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE
)
library(leaflet)
library(tibble)
library(plotKML)
```

```{r map_data}
iconen <- iconList(
  infobord = makeIcon("images/icon_bat.png", iconWidth = 32, iconHeight = 32),
  wegwijzer = makeIcon("images/icon_wegwijzer.png", iconWidth = 32, iconHeight = 32),
  koffie = makeIcon("images/icon_koffie.png", iconWidth = 32, iconHeight = 32),
  eten = makeIcon("images/icon_eten.png", iconWidth = 32, iconHeight = 32),
  info = makeIcon("images/icon_info.png", iconWidth = 32, iconHeight = 32)
)
punten <- tribble(
  ~omschrijving, ~lat, ~long, ~icoon,
  "Grote Zenne", 50.708614, 4.230570, "infobord",  
  "Kasteelpark Lembeek", 50.713455, 4.225291, "infobord", 
  "Bunker Colruyt", 50.728402, 4.223548, "infobord", 
  "Oude spoorweg", 50.730955, 4.219671, "infobord", 
  "Bunker kerkhof", 50.746620, 4.229127, "infobord", 
  "Bunker Jambonstraat", 50.748987, 4.237973, "infobord", 
  "Sint Vincentiuskerk", 50.740913, 4.249800, "infobord", 
  "Den Herberg", 50.741806, 4.250804, "koffie",
  "Alsput", 50.750371, 4.231023, "eten",
  "Toerisme Halle", 50.736003, 4.237707, "info"
)
route <- readGPX("route/route.gpx")$tracks[[1]][[1]]
```

```{r}
leaflet(data = punten) %>%
  addProviderTiles("Thunderforest.OpenCycleMap") %>%
  addPolylines(~lon, ~lat, data = route) %>%
  addMarkers(~long, ~lat, popup = ~omschrijving, icon = ~iconen[icoon])
```
